import { T, COMMIT } from './common.mjs';

export const afiliados = {
  type: 'afiliados',
  theme: 'theme-teal',
  slug: { es: 'marketing-de-afiliados', en: 'en/affiliate-marketing' },
  meta: {
    title: T('Marketing de afiliados medido en ingresos | VERTIAN SOLUTIONS', 'Affiliate marketing measured in revenue | VERTIAN SOLUTIONS'),
    description: T('Selección de programas de afiliación, contenido que convierte y seguimiento de comisiones. Panel con ingresos, coste y margen e informe mensual. En remoto para toda España.', 'Affiliate program selection, content that converts and commission tracking. Dashboard with revenue, cost and margin plus a monthly report. Remote, across Spain.'),
    ogTitle: T('Marketing de afiliados · VERTIAN SOLUTIONS', 'Affiliate marketing · VERTIAN SOLUTIONS'),
    ogDesc: T('Medimos lo que ingresa, no lo que gusta. Panel de ingresos, coste y margen.', 'We measure what earns, not what gets likes. Revenue, cost and margin dashboard.'),
    ogImage: 'assets/img/og-afiliados.jpg',
  },
  jsonld: {
    '@context': 'https://schema.org', '@type': 'ProfessionalService',
    name: 'VERTIAN SOLUTIONS, S.L. · Marketing de afiliados',
    areaServed: { '@type': 'Country', name: 'España' },
  },
  nav: [
    { href: '#panel', short: T('PANEL', 'DASHBOARD'), long: T('Panel de métricas', 'Metrics dashboard') },
    { href: '#servicios', short: T('SERVICIOS', 'SERVICES'), long: T('Servicios', 'Services') },
    { href: '#proceso', short: T('PROCESO', 'PROCESS'), long: T('Proceso', 'Process') },
    { href: '#empresa', short: T('EMPRESA', 'COMPANY'), long: T('La empresa', 'The company') },
    { href: '#opiniones', short: T('OPINIONES', 'REVIEWS'), long: T('Opiniones', 'Reviews') },
    { href: '#preguntas', short: T('PREGUNTAS', 'FAQ'), long: T('Preguntas frecuentes', 'Frequently asked questions') },
  ],
  hero: {
    kicker: T('MARKETING DE AFILIADOS', 'AFFILIATE MARKETING'),
    region: T('EN REMOTO · TODA ESPAÑA', 'REMOTE · ALL OF SPAIN'),
    h1: T('Medimos lo que <em>ingresa</em>, no lo que gusta.', 'We measure what <em>earns</em>, not what gets likes.'),
    lead: T('Elegimos los programas de afiliación que encajan con tu público, creamos el contenido que convierte y seguimos cada comisión. Cada mes ves ingresos, coste y margen.', 'We pick the affiliate programs that fit your audience, create content that converts and track every commission. Each month you see revenue, cost and margin.'),
    cta1: { href: '#panel', label: T('Ver el panel', 'See the dashboard'), arrow: '↓' },
    img: { id: 'afiliados-hero', ph: T('Foto horizontal: pantalla con métricas o persona creando contenido', 'Landscape photo: screen with metrics or a person creating content') },
    facts: [
      { k: T('MODALIDAD', 'FORMAT'), v: T('Remoto', 'Remote') },
      { k: T('INFORME', 'REPORT'), v: T('Mensual', 'Monthly') },
      { k: T('PERMANENCIA', 'LOCK-IN'), v: T('Ninguna', 'None'), hl: true },
    ],
  },
  commit: COMMIT(T('Sin extras. Cuota cerrada por escrito.', 'No extras. Fixed fee in writing.')),
  panel: {
    num: T('01 · PANEL DE MÉTRICAS', '01 · METRICS DASHBOARD'),
    h: T('Esto es lo que ves cada día.', 'This is what you see every day.'),
    lead: T('Tu panel muestra ingresos, coste y margen de cada programa. No hay seguidores ni «me gusta»: solo lo que entra en tu cuenta.', 'Your dashboard shows revenue, cost and margin for each program. No followers or likes: only what lands in your account.'),
    periodAria: T('Periodo', 'Period'),
    periods: [T('ÚLTIMO MES', 'LAST MONTH'), T('TRIMESTRE', 'QUARTER')],
    sample: T('DATOS DE EJEMPLO', 'SAMPLE DATA'),
    income: T('INGRESOS', 'REVENUE'),
    cost: T('COSTE', 'COST'),
    byProgram: T('POR PROGRAMA', 'BY PROGRAM'),
    program: T('PROGRAMA', 'PROGRAM'),
    margin: T('MARGEN', 'MARGIN'),
    reportH: T('INFORME MENSUAL · ANTES DEL DÍA 5', 'MONTHLY REPORT · BEFORE THE 5TH'),
    report: [T('Ingresos, coste y margen por programa', 'Revenue, cost and margin by program'), T('Contenidos publicados y su rendimiento', 'Published content and how it performed'), T('Qué dejamos, qué probamos el mes siguiente', 'What we drop and what we test next month')],
  },
  services: {
    num: T('02 · SERVICIOS', '02 · SERVICES'),
    h: T('Precios de partida.', 'Starting prices.'),
    items: [
      { code: 'AF-01', h: T('Auditoría y selección de programas', 'Audit and program selection'), p: T('Analizamos tu público y elegimos los programas con mejor comisión y condiciones de pago.', 'We analyse your audience and choose the programs with the best commission and payment terms.'), n: T('290 €', '€290'), pre: 'from', post: T('pago único', 'one-off') },
      { code: 'AF-02', h: T('Contenido que convierte', 'Content that converts'), p: T('Comparativas, guías y reseñas pensadas para que el lector compre, con enlaces medidos.', 'Comparisons, guides and reviews designed to help readers buy, with tracked links.'), n: T('450 €', '€450'), pre: 'from', post: T('/ mes', '/ month') },
      { code: 'AF-03', h: T('Seguimiento y panel', 'Tracking and dashboard'), p: T('Unimos tus programas en un panel con ingresos, coste y margen. Informe mensual incluido.', 'We bring your programs into one dashboard with revenue, cost and margin. Monthly report included.'), n: T('120 €', '€120'), pre: 'from', post: T('/ mes', '/ month') },
      { code: 'AF-04', h: T('Gestión completa', 'Full management'), p: T('Programas, contenido y seguimiento. Tú revisas el informe y decides.', 'Programs, content and tracking. You review the report and decide.'), n: T('690 €', '€690'), pre: 'from', post: T('/ mes', '/ month') },
    ],
    foot: T('Precios sin IVA. Sin permanencia: se cancela con 30 días de aviso.', 'Prices exclude VAT. No lock-in: cancel with 30 days’ notice.'),
  },
  explain: {
    num: T('03 · CÓMO FUNCIONA', '03 · HOW IT WORKS'),
    h: T('Cobras una comisión cada vez que alguien compra desde tu enlace.', 'You earn a commission every time someone buys through your link.'),
    paras: [
      T('Las marcas pagan por ventas, no por visitas. Por eso el trabajo está en tres cosas: elegir programas que paguen bien, escribir contenido que ayude a decidir y medir qué enlaces generan dinero.', 'Brands pay for sales, not visits. So the work comes down to three things: choosing programs that pay well, writing content that helps people decide and measuring which links make money.'),
      T('Las cuentas de afiliación están a tu nombre. Las comisiones te las pagan a ti. Nosotros cobramos una cuota fija que ves antes de empezar.', 'The affiliate accounts are in your name. Commissions are paid to you. We charge a fixed fee you see before we start.'),
    ],
    img: { id: 'afiliados-explica', ph: T('Foto: persona revisando un informe en el portátil', 'Photo: person reviewing a report on a laptop'), capR: T('INFORME MENSUAL', 'MONTHLY REPORT') },
    dl: [
      [T('QUÉ MEDIMOS', 'WHAT WE MEASURE'), T('Ingresos, coste, margen, clics y conversión', 'Revenue, cost, margin, clicks and conversion')],
      [T('QUÉ NO', 'WHAT WE DON’T'), T('Seguidores, «me gusta» o alcance sin ventas', 'Followers, likes or reach without sales')],
      [T('TRANSPARENCIA', 'TRANSPARENCY'), T('Los enlaces patrocinados se señalan, como exige la ley', 'Sponsored links are disclosed, as the law requires')],
    ],
  },
  process: {
    id: 'proceso',
    num: T('04 · PROCESO', '04 · PROCESS'),
    h: T('Tres pasos. Tú decides en cada uno.', 'Three steps. You decide at each one.'),
    steps: [
      { when: T('SEMANA 1', 'WEEK 1'), h: T('Auditoría', 'Audit'), p: T('Revisamos tu público, tu web o tus redes y te proponemos programas con cifras de comisión reales.', 'We review your audience, website or social channels and propose programs with real commission figures.') },
      { when: T('SEMANAS 2–4', 'WEEKS 2–4'), h: T('Contenido y enlaces', 'Content and links'), p: T('Publicamos el primer bloque de contenido con cada enlace etiquetado para medirlo.', 'We publish the first batch of content with every link tagged so it can be measured.') },
      { when: T('CADA MES', 'EVERY MONTH'), h: T('Medir y ajustar', 'Measure and adjust'), p: T('Informe antes del día 5. Lo que no genera margen, se cambia.', 'Report before the 5th. Whatever doesn’t make margin gets changed.') },
    ],
  },
  guarantees: {
    num: T('05 · GARANTÍAS', '05 · GUARANTEES'),
    h: T('Por escrito, en el contrato.', 'In writing, in the contract.'),
    items: [
      { t: T('Sin permanencia', 'No lock-in'), p: T('Mes a mes. Lo cancelas con 30 días de aviso, sin penalización.', 'Month to month. Cancel with 30 days’ notice, no penalty.') },
      { t: T('Acceso al panel', 'Dashboard access'), p: T('Ves tus datos cuando quieras, no solo cuando te mandamos el informe.', 'See your data whenever you like, not only when we send the report.') },
      { t: T('Informe antes del día 5', 'Report before the 5th'), p: T('Si llega tarde, ese mes no pagas la cuota de seguimiento.', 'If it’s late, you don’t pay the tracking fee that month.') },
      { t: T('Todo es tuyo', 'It’s all yours'), p: T('Contenido, cuentas de afiliación y datos quedan a tu nombre si lo dejas.', 'Content, affiliate accounts and data stay in your name if you leave.') },
    ],
  },
  company: {
    num: T('06 · LA EMPRESA', '06 · THE COMPANY'),
    p2: T('Todavía no tenemos una cartera larga de clientes, así que no te pedimos que nos creas. Te enseñamos los números y te dejamos irte cuando quieras.', 'We don’t have a long client list yet, so we don’t ask you to take our word for it. We show you the numbers and let you leave whenever you want.'),
    person: {
      img: { id: 'afiliados-responsable', ph: T('Retrato del responsable', 'Account manager portrait') },
      label: T('QUIÉN LLEVA TU CUENTA', 'WHO RUNS YOUR ACCOUNT'),
      name: T('[Nombre y apellidos]', '[Full name]'),
      role: T('[Cargo] · [Formación o certificaciones]', '[Role] · [Training or certifications]'),
      bio: T('[Dos líneas sobre tu experiencia en marketing y analítica.]', '[Two lines about your experience in marketing and analytics.]'),
    },
    extraRows: [],
    nots: [
      T('Comprar seguidores ni tráfico falso.', 'Buying followers or fake traffic.'),
      T('Prometerte una cifra de ingresos antes de medir.', 'Promising you a revenue figure before measuring.'),
      T('Publicar opiniones que no sean de clientes reales.', 'Publishing reviews that aren’t from real clients.'),
    ],
  },
  reviews: {
    num: T('07 · OPINIONES DE CLIENTES', '07 · CLIENT REVIEWS'),
    h: T('Lo que dicen quienes ya trabajan con nosotros.', 'What the people who work with us say.'),
    cap: T('[Nombre] · [Empresa o web] · [Fecha] · Google', '[Name] · [Company or website] · [Date] · Google'),
  },
  faq: {
    num: T('08 · PREGUNTAS FRECUENTES', '08 · FREQUENTLY ASKED QUESTIONS'),
    h: T('Las dudas antes de empezar.', 'Questions before you start.'),
    items: [
      [T('¿Cuándo empiezo a ver ingresos?', 'When will I start seeing revenue?'), T('No te damos una fecha que no podemos garantizar. Desde el primer mes ves en el panel clics y conversiones de cada enlace, así sabes si va por buen camino.', 'We won’t give you a date we can’t guarantee. From the first month you see clicks and conversions for every link in the dashboard, so you know whether it’s on track.')],
      [T('¿Necesito tener una web?', 'Do I need a website?'), T('Ayuda, pero no es obligatorio. También trabajamos con boletines, redes o canales de vídeo. En la auditoría te decimos qué canal tiene más sentido.', 'It helps, but it isn’t required. We also work with newsletters, social media and video channels. The audit tells you which channel makes most sense.')],
      [T('¿Quién cobra las comisiones?', 'Who gets paid the commissions?'), T('Tú. Las cuentas de afiliación están a tu nombre y las marcas te pagan directamente. Nosotros facturamos solo la cuota acordada.', 'You do. The affiliate accounts are in your name and brands pay you directly. We only invoice the agreed fee.')],
      [T('¿Hay permanencia?', 'Is there a lock-in?'), T('No. Es mes a mes y se cancela con 30 días de aviso. El contenido publicado sigue siendo tuyo.', 'No. It’s month to month and you can cancel with 30 days’ notice. Published content remains yours.')],
      [T('¿Es legal? ¿Hay que avisar de los enlaces?', 'Is it legal? Do links need to be disclosed?'), T('Sí, es legal, y sí, hay que señalar la publicidad. Todo el contenido que hacemos identifica los enlaces de afiliado.', 'Yes, it’s legal, and yes, advertising must be disclosed. All the content we produce identifies affiliate links.')],
      [T('¿Por qué fiarme de una empresa nueva?', 'Why trust a new company?'), T('Porque no tienes que hacerlo a ciegas: ves los datos en tu panel, no hay permanencia y todo lo que creamos queda a tu nombre.', 'Because you don’t have to do it blindly: you see the data in your dashboard, there’s no lock-in and everything we create stays in your name.')],
    ],
  },
  contact: {
    num: T('09 · CONTACTO', '09 · CONTACT'),
    lead: T('Cuéntanos tu canal y tu público. Te contestamos en 24 h en día laborable.', 'Tell us about your channel and audience. We reply within one working day.'),
    services: [T('Auditoría y selección de programas', 'Audit and program selection'), T('Contenido que convierte', 'Content that converts'), T('Seguimiento y panel', 'Tracking and dashboard'), T('Gestión completa', 'Full management')],
  },
  footer: { tagline: T('Marketing de afiliados en remoto para toda España.', 'Remote affiliate marketing across Spain.'), tag: T('AFILIADOS', 'AFFILIATES') },
  js: {
    months: T(['E', 'F', 'M', 'A', 'M', 'J', 'J', 'A', 'S', 'O', 'N', 'D'], ['J', 'F', 'M', 'A', 'M', 'J', 'J', 'A', 'S', 'O', 'N', 'D']),
    ing: [620, 890, 1240, 1510, 1980, 2310, 2650, 3120, 3480, 3950, 4410, 4820],
    cost: [690, 690, 690, 740, 740, 740, 790, 790, 790, 840, 840, 840],
    progs: [[T('Programa A · Hogar', 'Program A · Home'), .38], [T('Programa B · Tecnología', 'Program B · Tech'), .29], [T('Programa C · Viajes', 'Program C · Travel'), .21], [T('Programa D · Formación', 'Program D · Education'), .12]],
    i18n: {
      income: T('Ingresos', 'Revenue'),
      vsPrev: T('vs. anterior', 'vs. previous'),
      cost: T('Coste', 'Cost'),
      costSub: T('cuota + herramientas', 'fee + tools'),
      margin: T('Margen', 'Margin'),
      marginSub: T('sobre ingresos', 'of revenue'),
      clicks: T('Clics en enlaces', 'Link clicks'),
      clicksSub: T('medidos por enlace', 'tracked per link'),
      conv: T('Conversión', 'Conversion'),
      convSub: T('clic → venta', 'click → sale'),
      epc: T('Ingreso por clic', 'Earnings per click'),
    },
  },
};
