// Páginas de certificados energéticos. Gijón y Alzira comparten todo salvo la zona.
import { T, COMMIT } from './common.mjs';

const TIPOS = [
  { id: 'piso', code: 'CEE-01', base: 90, label: T('Piso', 'Flat'), svc: T('Certificado · Piso o apartamento', 'Certificate · Flat or apartment') },
  { id: 'casa', code: 'CEE-02', base: 140, label: T('Casa o chalet', 'House or villa'), svc: T('Certificado · Casa o chalet', 'Certificate · House or villa') },
  { id: 'local', code: 'CEE-03', base: 150, label: T('Local u oficina', 'Shop or office'), svc: T('Certificado · Local u oficina', 'Certificate · Shop or office') },
  { id: 'edificio', code: 'CEE-04', base: 390, label: T('Edificio', 'Building'), svc: T('Certificado · Edificio completo', 'Certificate · Whole building') },
];

const LETTERS = [
  { k: 'A', c: '#00913F', fg: '#fff', t: T('Consumo muy bajo. Habitual en obra nueva reciente o tras una rehabilitación profunda.', 'Very low consumption. Typical of recent new builds or after a deep renovation.') },
  { k: 'B', c: '#4DA838', fg: '#fff', t: T('Consumo bajo. Buen aislamiento y equipos eficientes.', 'Low consumption. Good insulation and efficient systems.') },
  { k: 'C', c: '#BDCF1E', fg: '#0F2232', t: T('Edificios construidos con el Código Técnico de 2006 o posteriores suelen estar aquí.', 'Buildings built under the 2006 Technical Building Code or later usually land here.') },
  { k: 'D', c: '#F2DE00', fg: '#0F2232', t: T('Consumo medio. Algo de aislamiento o ventanas renovadas.', 'Average consumption. Some insulation or replaced windows.') },
  { k: 'E', c: '#F7B500', fg: '#0F2232', t: T('La letra más frecuente en viviendas existentes en España.', 'The most common rating for existing homes in Spain.') },
  { k: 'F', c: '#E8660A', fg: '#fff', t: T('Consumo alto. Poco aislamiento y equipos antiguos.', 'High consumption. Little insulation and old systems.') },
  { k: 'G', c: '#D7141A', fg: '#fff', t: T('Consumo muy alto. Frecuente en edificios anteriores a 1979, año de la primera norma térmica. El certificado dura 5 años.', 'Very high consumption. Common in buildings from before 1979, the year of the first thermal regulation. The certificate lasts 5 years.') },
];

export function certPage(c) {
  const Z = c.zoneWord;
  return {
    type: 'cert',
    theme: 'theme-green',
    slug: c.slug,
    meta: c.meta,
    jsonld: {
      '@context': 'https://schema.org', '@type': 'ProfessionalService',
      name: `VERTIAN SOLUTIONS, S.L. · ${c.jsonName}`,
      priceRange: '€€',
      address: { '@type': 'PostalAddress', addressLocality: c.city, addressRegion: c.region, postalCode: c.postal, addressCountry: 'ES' },
      geo: { '@type': 'GeoCoordinates', latitude: c.geo[0], longitude: c.geo[1] },
      areaServed: c.areaServed,
      openingHoursSpecification: [{ '@type': 'OpeningHoursSpecification', dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'], opens: '09:00', closes: '19:00' }],
    },
    nav: [
      { href: '#precio', short: T('PRECIO', 'PRICE'), long: T('Calcular precio', 'Price calculator') },
      { href: '#servicios', short: T('SERVICIOS', 'SERVICES'), long: T('Servicios', 'Services') },
      { href: '#zona', short: T('ZONA', 'AREA'), long: T('Zona de trabajo', 'Service area') },
      { href: '#empresa', short: T('EMPRESA', 'COMPANY'), long: T('La empresa', 'The company') },
      { href: '#opiniones', short: T('OPINIONES', 'REVIEWS'), long: T('Opiniones', 'Reviews') },
      { href: '#preguntas', short: T('PREGUNTAS', 'FAQ'), long: T('Preguntas frecuentes', 'Frequently asked questions') },
    ],
    hero: {
      kicker: T('CERTIFICADOS ENERGÉTICOS', 'ENERGY PERFORMANCE CERTIFICATES'),
      region: c.kickerRegion,
      h1: c.h1,
      lead: c.lead,
      cta1: { href: '#precio', label: T('Calcular mi precio', 'Work out my price'), arrow: '→' },
      img: { id: `${c.key}-hero`, ph: c.heroPh },
      facts: [
        { k: T('VISITA', 'VISIT'), v: '30–60 min' },
        { k: T('ENTREGA', 'DELIVERY'), v: T('≤ 5 días hábiles', '≤ 5 working days') },
        { k: T('VALIDEZ', 'VALID FOR'), v: T('10 años', '10 years'), hl: true },
      ],
    },
    commit: COMMIT(T('Sin extras. El presupuesto que firmas es el que pagas.', 'No extras. The quote you sign is what you pay.')),
    calc: {
      num: T('01 · CALCULADORA', '01 · CALCULATOR'),
      h: T('Tu precio en tres preguntas.', 'Your price in three questions.'),
      lead: T('Toca las opciones o dícelo en voz alta. El precio cambia con cada respuesta y te lo confirmamos por escrito en 24 h.', 'Tap the options or just say it out loud. The price updates with every answer and we confirm it in writing within 24 h.'),
      voiceT: T('Descríbelo por voz', 'Describe it by voice'),
      voiceAria: T('Describir el inmueble por voz', 'Describe the property by voice'),
      l1: T('01 · TIPO DE INMUEBLE', '01 · PROPERTY TYPE'),
      l2: c.l2,
      l3: T('03 · PARA QUÉ Y CUÁNDO', '03 · WHAT FOR AND WHEN'),
      sup: T('Superficie construida', 'Built area'),
      zone: Z,
      resHead: T('PRECIO ORIENTATIVO', 'ESTIMATED PRICE'),
      example: T('CIFRAS DE EJEMPLO', 'SAMPLE FIGURES'),
      unit: T('€ + IVA', '€ + VAT'),
      send: T('Pedir el precio cerrado', 'Get a fixed quote'),
      fine: T('Pasamos estos datos al formulario. Solo añades tu nombre y contacto.', 'We copy these details into the form. You just add your name and contact details.'),
    },
    services: {
      num: T('02 · SERVICIOS', '02 · SERVICES'),
      h: T('Precios de partida.', 'Starting prices.'),
      items: [
        { code: 'CEE-01', h: T('Piso o apartamento', 'Flat or apartment'), p: T('Para vender o alquilar una vivienda en un edificio. Hasta 100 m².', 'To sell or rent a home in an apartment block. Up to 100 m².'), n: T('90 €', '€90'), pre: 'from', post: 'vat' },
        { code: 'CEE-02', h: T('Casa o chalet', 'House or villa'), p: T('Vivienda unifamiliar, aislada o adosada.', 'Detached or semi-detached single-family home.'), n: T('140 €', '€140'), pre: 'from', post: 'vat' },
        { code: 'CEE-03', h: T('Local u oficina', 'Shop or office'), p: T('Terciario pequeño. Se revisan climatización e iluminación.', 'Small commercial premises. Heating, cooling and lighting are checked.'), n: T('150 €', '€150'), pre: 'from', post: 'vat' },
        { code: 'CEE-04', h: T('Edificio completo', 'Whole building'), p: T('Comunidades de propietarios, para ayudas a la rehabilitación.', 'Owners’ associations applying for renovation grants.'), n: T('390 €', '€390'), pre: 'from', post: 'vat' },
      ],
      foot: T('Todos incluyen visita, cálculo con software reconocido por el Ministerio, etiqueta energética y trámite de registro.', 'All include the visit, calculation with Ministry-approved software, the energy label and registration.'),
    },
    explain: {
      num: T('03 · QUÉ ES', '03 · WHAT IT IS'),
      h: T('Una letra que tienes que enseñar para vender o alquilar.', 'A letter you must show to sell or rent.'),
      paras: [T('El certificado mide cuánta energía necesita el inmueble y cuánto CO₂ emite, y lo resume en una letra de la A a la G. Es obligatorio para vender o alquilar y la etiqueta debe aparecer en el anuncio. Toca una letra para ver qué significa.',
                'The certificate measures how much energy the property needs and how much CO₂ it emits, and sums it up as a letter from A to G. It is mandatory to sell or rent, and the label must appear in the listing. Tap a letter to see what it means.')],
      img: { id: `${c.key}-explica`, ph: c.explainPh, capR: c.figCap },
      letters: true,
      letterAria: T('Escala de calificación energética', 'Energy rating scale'),
      letterWord: T('LETRA', 'RATING'),
      dl: [
        [T('NORMA', 'REGULATION'), T('Real Decreto 390/2021', 'Royal Decree 390/2021')],
        [T('VALIDEZ', 'VALID FOR'), T('10 años (5 si la letra es G)', '10 years (5 if rated G)')],
        [T('REGISTRO', 'REGISTRY'), c.registry],
      ],
    },
    zone: {
      num: T('04 · ZONA DE TRABAJO', '04 · SERVICE AREA'),
      h: c.zoneH,
      p: c.zoneP,
      caption: c.zoneCaption,
      aria: c.hubAria,
    },
    process: {
      num: T('05 · PROCESO', '05 · PROCESS'),
      h: T('Tres pasos. Tú participas en uno.', 'Three steps. You only take part in one.'),
      steps: [
        { when: T('DÍA 0', 'DAY 0'), h: T('Pides precio', 'You ask for a price'), p: T('Con la calculadora o por teléfono. En 24 h tienes el presupuesto cerrado por escrito.', 'With the calculator or by phone. Within 24 h you get a fixed written quote.') },
        { when: T('DÍA 1–3', 'DAY 1–3'), h: T('Visitamos el inmueble', 'We visit the property'), p: T('Entre 30 y 60 minutos. Medimos y revisamos ventanas, caldera y aislamiento. Es la parte en la que estás tú.', 'Between 30 and 60 minutes. We measure and check windows, boiler and insulation. This is the part you’re there for.') },
        { when: T('DÍA 3–7', 'DAY 3–7'), h: T('Calculamos y registramos', 'We calculate and register'), p: T('Recibes el certificado en PDF, la etiqueta para el anuncio y el justificante de registro.', 'You receive the certificate as a PDF, the label for your listing and proof of registration.') },
      ],
    },
    guarantees: {
      num: T('06 · GARANTÍAS', '06 · GUARANTEES'),
      h: T('Por escrito, en el mismo presupuesto.', 'In writing, in the quote itself.'),
      items: [
        { t: T('Precio cerrado', 'Fixed price'), p: T('Si en la visita algo no coincide con lo que nos dijiste, te avisamos antes de seguir. Sin cargos sorpresa.', 'If something at the visit doesn’t match what you told us, we tell you before going on. No surprise charges.') },
        { t: T('Plazo de entrega', 'Delivery time'), p: T('Certificado entregado en un máximo de 5 días hábiles desde la visita.', 'Certificate delivered within 5 working days of the visit.') },
        { t: T('Corrección sin coste', 'Free corrections'), p: T('Si hay un error nuestro, lo corregimos y volvemos a registrar sin cobrarte.', 'If we make a mistake, we fix it and re-register at no charge.') },
        { t: T('Seguro de RC', 'Liability insurance'), p: T('Póliza de responsabilidad civil profesional. Te enviamos copia si la pides.', 'Professional liability policy. We’ll send you a copy on request.') },
      ],
    },
    company: {
      num: T('07 · LA EMPRESA', '07 · THE COMPANY'),
      p2: T('Todavía no tenemos una cartera larga de clientes, así que no te pedimos que nos creas. Te damos datos que puedes comprobar antes de contratar.', 'We don’t have a long client list yet, so we don’t ask you to take our word for it. We give you facts you can check before hiring us.'),
      person: {
        img: { id: `${c.key}-tecnico`, ph: T('Retrato del técnico', 'Technician portrait') },
        label: T('QUIÉN HACE TU CERTIFICADO', 'WHO DOES YOUR CERTIFICATE'),
        name: T('[Nombre y apellidos]', '[Full name]'),
        role: T('[Titulación] · Colegiado n.º [0000]', '[Qualification] · Registration no. [0000]'),
        bio: T('[Dos líneas sobre tu experiencia en edificación y eficiencia energética.]', '[Two lines about your experience in building and energy efficiency.]'),
      },
      extraRows: [[T('SOFTWARE', 'SOFTWARE'), T('Programas reconocidos por el Ministerio (CE3X, HULC o CYPETHERM)', 'Ministry-approved programs (CE3X, HULC or CYPETHERM)')]],
      nots: [
        T('Certificados sin visita al inmueble.', 'Certificates without visiting the property.'),
        T('Subir el precio después de la visita.', 'Raising the price after the visit.'),
        T('Publicar opiniones que no sean de clientes reales.', 'Publishing reviews that aren’t from real clients.'),
      ],
    },
    reviews: {
      num: T('08 · OPINIONES DE CLIENTES', '08 · CLIENT REVIEWS'),
      cap: T(`[Nombre] · [${Z.es}] · [Fecha] · Google`, `[Name] · [${Z.en}] · [Date] · Google`),
      foot: T('Solo publicamos opiniones de clientes reales, con nombre, fecha y enlace a la fuente. Si has trabajado con nosotros, puedes dejar la tuya en Google.', 'We only publish reviews from real clients, with name, date and a link to the source. If you’ve worked with us, you can leave yours on Google.'),
    },
    faq: {
      num: T('09 · PREGUNTAS FRECUENTES', '09 · FREQUENTLY ASKED QUESTIONS'),
      h: c.faqH,
      items: [
        [T('¿Hace falta visitar el inmueble? He visto certificados online sin visita.', 'Do you really need to visit? I’ve seen online certificates with no visit.'), T('Sí. El Real Decreto 390/2021 obliga a que el técnico visite el inmueble. Un certificado sin visita puede ser rechazado y te expone a una sanción.', 'Yes. Royal Decree 390/2021 requires the technician to visit the property. A certificate issued without a visit can be rejected and exposes you to a fine.')],
        [T('¿Cuánto tardáis en total?', 'How long does it take overall?'), T('Respondemos en 24 h, visitamos en 1 a 3 días y entregamos en un máximo de 5 días hábiles desde la visita. Con plazo urgente, 48 h desde la visita.', 'We reply within 24 h, visit within 1 to 3 days and deliver within 5 working days of the visit. With the urgent option, 48 h after the visit.')],
        [T('¿Y si me sale una letra mala?', 'What if I get a bad rating?'), T('Puedes vender o alquilar igual. El certificado incluye recomendaciones de mejora ordenadas por coste, útiles si piensas pedir ayudas a la rehabilitación.', 'You can still sell or rent. The certificate includes improvement recommendations sorted by cost, useful if you plan to apply for renovation grants.')],
        [T('¿Tengo que estar presente en la visita?', 'Do I have to be there for the visit?'), T('No hace falta que seas tú. Basta con que alguien nos abra: un familiar, el inquilino o tu inmobiliaria.', 'It doesn’t have to be you. Anyone who can let us in will do: a relative, the tenant or your estate agent.')],
        [T('¿Qué documentación necesito?', 'What documents do I need?'), T('La dirección y, si la tienes, la referencia catastral (aparece en el recibo del IBI). Si hay facturas de reformas de ventanas, caldera o aislamiento, ayudan a mejorar el resultado.', 'The address and, if you have it, the cadastral reference (it’s on the IBI property tax bill). Invoices for new windows, boiler or insulation help improve the result.')],
        [T('¿Por qué fiarme de una empresa nueva?', 'Why trust a new company?'), T('Porque todo lo que decimos se puede comprobar: CIF, domicilio, seguro de responsabilidad civil y técnico colegiado. Y porque el precio queda cerrado por escrito antes de la visita.', 'Because everything we say can be checked: tax ID, registered office, liability insurance and a registered technician. And because the price is fixed in writing before the visit.')],
      ],
    },
    contact: {
      num: T('10 · CONTACTO', '10 · CONTACT'),
      lead: T('Te contestamos en 24 h en día laborable con un precio cerrado.', 'We reply within one working day with a fixed price.'),
      hours: T('Lunes a viernes, 9:00–19:00', 'Monday to Friday, 9:00–19:00'),
      services: TIPOS.map(t => t.svc),
      dictate: true,
    },
    footer: { tagline: c.footTag, tag: `CEE · ${c.city.toUpperCase()}` },
    // Datos que necesita el JavaScript de la calculadora.
    js: {
      zoneWord: Z,
      tipos: TIPOS.map(t => ({ id: t.id, code: t.code, base: t.base, label: t.label, svc: t.svc })),
      zones: c.zones,
      fee: c.fee,
      barMax: c.barMax,
      mapLabels: c.mapLabels,
      aliases: c.aliases,
      letters: LETTERS,
      voiceExample: c.voiceExample,
      i18n: {
        motivos: [T('Venta', 'Sale'), T('Alquiler', 'Rental'), T('Ayudas o reforma', 'Grants or renovation')],
        plazos: [T('Normal · 5 días', 'Standard · 5 days'), T('Urgente · 48 h', 'Urgent · 48 h')],
        noSup: T('no aplica', 'n/a'),
        base: T('base', 'base'),
        surface: T('Superficie', 'Area'),
        travel: T('Desplazamiento', 'Travel'),
        term: T('Plazo', 'Turnaround'),
        included: T('incluido', 'included'),
        listening: T('Escuchando… habla con normalidad.', 'Listening… speak normally.'),
        noPerm: T('Sin permiso de micrófono. Puedes tocar las opciones.', 'No microphone permission. You can tap the options instead.'),
        noUnderstand: T('No te hemos entendido. Prueba otra vez.', 'We didn’t catch that. Please try again.'),
        noVoice: T('Tu navegador no permite dictado. Prueba con Chrome, Edge o Safari, o toca las opciones.', 'Your browser doesn’t support dictation. Try Chrome, Edge or Safari, or tap the options.'),
        msgHead: T('Datos de la calculadora:', 'Calculator details:'),
        msgType: T('Inmueble', 'Property'),
        msgReason: T('Motivo', 'Purpose'),
        msgTerm: T('Plazo', 'Turnaround'),
        msgNormal: T('Normal (5 días)', 'Standard (5 days)'),
        msgUrgent: T('Urgente (48 h)', 'Urgent (48 h)'),
        msgPrice: T('Precio orientativo', 'Estimated price'),
        vat: T('€ + IVA', '€ + VAT'),
      },
    },
  };
}

export const gijon = certPage({
  key: 'gijon',
  city: 'Gijón',
  region: 'Asturias',
  postal: '33200',
  geo: [43.5322, -5.6611],
  slug: { es: 'certificado-energetico-gijon', en: 'en/energy-certificate-gijon' },
  jsonName: 'Certificados energéticos Gijón',
  areaServed: ['Gijón', 'Carreño', 'Avilés', 'Corvera de Asturias', 'Llanera', 'Oviedo', 'Siero', 'Sariego', 'Villaviciosa', 'Nava'],
  meta: {
    title: T('Certificado energético en Gijón | Visita, cálculo y registro | VERTIAN', 'Energy certificate in Gijón | Visit, calculation and registration | VERTIAN'),
    description: T('Certificado de eficiencia energética en Gijón y concejos cercanos. Visita al inmueble, cálculo con software oficial y registro en el Principado de Asturias. Precio cerrado y respuesta en 24 h.', 'Energy performance certificate in Gijón and nearby municipalities. On-site visit, calculation with official software and registration with the Principality of Asturias. Fixed price and a reply within 24 h.'),
    ogTitle: T('Certificado energético en Gijón · VERTIAN SOLUTIONS', 'Energy certificate in Gijón · VERTIAN SOLUTIONS'),
    ogDesc: T('Visita, cálculo con software oficial y registro. Precio cerrado antes de empezar.', 'Visit, calculation with official software and registration. Fixed price before we start.'),
    ogImage: 'assets/img/og-gijon.jpg',
  },
  kickerRegion: T('GIJÓN Y CONCEJOS CERCANOS · ASTURIAS', 'GIJÓN AND NEARBY AREAS · ASTURIAS'),
  h1: T('Certificado energético en Gijón. <em>Precio cerrado</em> antes de la visita.', 'Energy certificate in Gijón. <em>Fixed price</em> before the visit.'),
  lead: T('Vamos al inmueble, lo medimos, hacemos el cálculo con software oficial y lo registramos en el Principado de Asturias. Tú solo nos abres la puerta.', 'We visit the property, measure it, run the calculation with official software and register it with the Principality of Asturias. All you do is open the door.'),
  heroPh: T('Foto horizontal: técnico midiendo una vivienda en Gijón', 'Landscape photo: technician measuring a home in Gijón'),
  explainPh: T('Foto: fachada de edificio residencial en Gijón', 'Photo: residential building façade in Gijón'),
  figCap: T('GIJÓN · ASTURIAS', 'GIJÓN · ASTURIAS'),
  zoneWord: T('Concejo', 'Municipality'),
  l2: T('02 · SUPERFICIE Y CONCEJO', '02 · AREA AND MUNICIPALITY'),
  registry: T('Principado de Asturias', 'Principality of Asturias'),
  zoneH: T('Gijón y nueve concejos alrededor.', 'Gijón and nine surrounding municipalities.'),
  zoneP: T('Hasta 20 km el desplazamiento va incluido. Más allá, lo ves sumado en la calculadora antes de pedir nada.', 'Travel is included up to 20 km. Beyond that, you see it added in the calculator before you ask for anything.'),
  zoneCaption: T('KM APROXIMADOS DESDE GIJÓN · DESPLAZAMIENTO (EJEMPLO)', 'APPROX. KM FROM GIJÓN · TRAVEL FEE (SAMPLE)'),
  hubAria: T('Diagrama de distancias desde Gijón a los concejos donde trabajamos. Zona de 20 km con desplazamiento incluido.', 'Distance diagram from Gijón to the municipalities we cover. 20 km zone with travel included.'),
  faqH: T('Lo que nos suelen preguntar en Gijón.', 'What people in Gijón usually ask us.'),
  footTag: T('Certificados energéticos en Gijón y concejos cercanos.', 'Energy certificates in Gijón and nearby municipalities.'),
  voiceExample: T('Por ejemplo: «Piso de 85 metros en Siero, para alquilar».', 'For example: “85 square metre flat in Siero, to rent”.'),
  // km aproximados por carretera; dx/dy en km para el diagrama (norte arriba)
  zones: [
    { name: 'Gijón', km: 0, dx: 0, dy: 0 },
    { name: 'Carreño', km: 14, dx: -12, dy: -2 },
    { name: 'Siero', km: 20, dx: 3, dy: 18 },
    { name: 'Sariego', km: 21, dx: 9, dy: 15 },
    { name: 'Llanera', km: 22, dx: -12, dy: 15 },
    { name: 'Corvera', km: 23, dx: -19, dy: 8 },
    { name: 'Avilés', km: 25, dx: -23, dy: 2 },
    { name: 'Oviedo', km: 29, dx: -7, dy: 25 },
    { name: 'Villaviciosa', km: 30, dx: 24, dy: 4 },
    { name: 'Nava', km: 34, dx: 16, dy: 24 },
  ],
  // [hasta km, recargo €]: hasta 20 km incluido, hasta 30 km +15 €, más allá +25 €
  fee: [[20, 0], [30, 15], [Infinity, 25]],
  barMax: 34,
  mapLabels: [{ t: T('N · MAR CANTÁBRICO', 'N · BAY OF BISCAY'), x: 0, y: -334, a: 'middle' }],
  aliases: [['pola de siero|lugones', 'Siero'], ['candas', 'Carreño'], ['luanco', 'Gijón']],
});

export const alzira = certPage({
  key: 'alzira',
  city: 'Alzira',
  region: 'Valencia',
  postal: '46600',
  geo: [39.1510, -0.4356],
  slug: { es: 'certificado-energetico-alzira', en: 'en/energy-certificate-alzira' },
  jsonName: 'Certificados energéticos Alzira',
  areaServed: ['Alzira', 'Carcaixent', 'Guadassuar', "l'Alcúdia", 'Algemesí', 'Alberic', 'Carlet', 'Castelló', 'Alginet', 'Benifaió'],
  meta: {
    title: T('Certificado energético en Alzira | Visita, cálculo y registro | VERTIAN', 'Energy certificate in Alzira | Visit, calculation and registration | VERTIAN'),
    description: T('Certificado de eficiencia energética en Alzira y la Ribera Alta. Visita al inmueble, cálculo con software oficial y registro en la Comunitat Valenciana. Precio cerrado y respuesta en 24 h.', 'Energy performance certificate in Alzira and the Ribera Alta. On-site visit, calculation with official software and registration in the Valencian Community. Fixed price and a reply within 24 h.'),
    ogTitle: T('Certificado energético en Alzira · VERTIAN SOLUTIONS', 'Energy certificate in Alzira · VERTIAN SOLUTIONS'),
    ogDesc: T('Visita, cálculo con software oficial y registro. Precio cerrado antes de empezar.', 'Visit, calculation with official software and registration. Fixed price before we start.'),
    ogImage: 'assets/img/og-alzira.jpg',
  },
  kickerRegion: T('ALZIRA Y LA RIBERA ALTA · VALENCIA', 'ALZIRA AND THE RIBERA ALTA · VALENCIA'),
  h1: T('Certificado energético en Alzira. <em>Precio cerrado</em> antes de la visita.', 'Energy certificate in Alzira. <em>Fixed price</em> before the visit.'),
  lead: T('Vamos al inmueble, lo medimos, hacemos el cálculo con software oficial y lo registramos en la Comunitat Valenciana. Tú solo nos abres la puerta.', 'We visit the property, measure it, run the calculation with official software and register it with the Valencian Community. All you do is open the door.'),
  heroPh: T('Foto horizontal: técnico midiendo una vivienda en Alzira', 'Landscape photo: technician measuring a home in Alzira'),
  explainPh: T('Foto: fachada de edificio residencial en Alzira', 'Photo: residential building façade in Alzira'),
  figCap: T('ALZIRA · VALENCIA', 'ALZIRA · VALENCIA'),
  zoneWord: T('Municipio', 'Town'),
  l2: T('02 · SUPERFICIE Y MUNICIPIO', '02 · AREA AND TOWN'),
  registry: T('Comunitat Valenciana (IVACE)', 'Valencian Community (IVACE)'),
  zoneH: T('Alzira y nueve municipios de la Ribera Alta.', 'Alzira and nine towns in the Ribera Alta.'),
  zoneP: T('Hasta 15 km el desplazamiento va incluido. Más allá, lo ves sumado en la calculadora antes de pedir nada.', 'Travel is included up to 15 km. Beyond that, you see it added in the calculator before you ask for anything.'),
  zoneCaption: T('KM APROXIMADOS DESDE ALZIRA · DESPLAZAMIENTO (EJEMPLO)', 'APPROX. KM FROM ALZIRA · TRAVEL FEE (SAMPLE)'),
  hubAria: T('Diagrama de distancias desde Alzira a los municipios de la Ribera Alta donde trabajamos. Zona de 15 km con desplazamiento incluido.', 'Distance diagram from Alzira to the Ribera Alta towns we cover. 15 km zone with travel included.'),
  faqH: T('Lo que nos suelen preguntar en la Ribera.', 'What people in the Ribera usually ask us.'),
  footTag: T('Certificados energéticos en Alzira y la Ribera Alta.', 'Energy certificates in Alzira and the Ribera Alta.'),
  voiceExample: T('Por ejemplo: «Piso de 85 metros en Algemesí, para alquilar».', 'For example: “85 square metre flat in Algemesí, to rent”.'),
  zones: [
    { name: 'Alzira', km: 0, dx: 0, dy: 0 },
    { name: 'Carcaixent', km: 6, dx: 5, dy: 3 },
    { name: 'Guadassuar', km: 8, dx: -6, dy: -5 },
    { name: "l'Alcúdia", km: 11, dx: -9, dy: -7 },
    { name: 'Algemesí', km: 12, dx: 2, dy: -11 },
    { name: 'Alberic', km: 13, dx: -9, dy: 10 },
    { name: 'Carlet', km: 16, dx: -13, dy: -10 },
    { name: 'Castelló', km: 17, dx: -13, dy: 12 },
    { name: 'Alginet', km: 18, dx: -5, dy: -16 },
    { name: 'Benifaió', km: 22, dx: -3, dy: -20 },
  ],
  // hasta 15 km incluido, más allá +15 €
  fee: [[15, 0], [Infinity, 15]],
  barMax: 22,
  mapLabels: [{ t: T('N', 'N'), x: 0, y: -334, a: 'middle' }, { t: T('MAR MEDITERRÁNEO →', 'MEDITERRANEAN SEA →'), x: 330, y: 4, a: 'end' }],
  aliases: [['alcudia', "l'Alcúdia"], ['castellon|vilanova de castello|villanueva de castellon', 'Castelló'], ['benifayo', 'Benifaió'], ['algemesi', 'Algemesí']],
});
