import { T, COMMIT } from './common.mjs';

export const ia = {
  type: 'ia',
  theme: 'theme-blue',
  slug: { es: 'apps-automatizacion-ia', en: 'en/apps-ai-automation' },
  meta: {
    title: T('Apps y automatización con IA para pymes | VERTIAN SOLUTIONS', 'Apps and AI automation for small businesses | VERTIAN SOLUTIONS'),
    description: T('Aplicaciones a medida y automatización con IA para pymes: presupuestos, facturación, citas, atención al cliente, entrada de datos e informes. Horas ahorradas y plazo de amortización por escrito.', 'Custom apps and AI automation for small businesses: quotes, invoicing, appointments, customer service, data entry and reports. Hours saved and payback period in writing.'),
    ogTitle: T('Apps y automatización con IA · VERTIAN SOLUTIONS', 'Apps and AI automation · VERTIAN SOLUTIONS'),
    ogDesc: T('Cuántas horas ahorras y en qué plazo se paga, antes de empezar.', 'How many hours you save and when it pays for itself, before we start.'),
    ogImage: 'assets/img/og-ia.jpg',
  },
  jsonld: {
    '@context': 'https://schema.org', '@type': 'ProfessionalService',
    name: 'VERTIAN SOLUTIONS, S.L. · Apps y automatización con IA',
    areaServed: { '@type': 'Country', name: 'España' },
  },
  nav: [
    { href: '#calculadora', short: T('AHORRO', 'SAVINGS'), long: T('Calcula tu ahorro', 'Work out your savings') },
    { href: '#servicios', short: T('SERVICIOS', 'SERVICES'), long: T('Servicios', 'Services') },
    { href: '#proceso', short: T('PROCESO', 'PROCESS'), long: T('Proceso', 'Process') },
    { href: '#empresa', short: T('EMPRESA', 'COMPANY'), long: T('La empresa', 'The company') },
    { href: '#opiniones', short: T('OPINIONES', 'REVIEWS'), long: T('Opiniones', 'Reviews') },
    { href: '#preguntas', short: T('PREGUNTAS', 'FAQ'), long: T('Preguntas frecuentes', 'Frequently asked questions') },
  ],
  hero: {
    kicker: T('APPS Y AUTOMATIZACIÓN CON IA', 'APPS AND AI AUTOMATION'),
    region: T('PARA PYMES · TODA ESPAÑA', 'FOR SMALL BUSINESSES · ALL OF SPAIN'),
    h1: T('Horas que vuelven a tu semana. <em>Con fecha</em> de amortización.', 'Hours back in your week. <em>With a</em> payback date.'),
    lead: T('Hacemos aplicaciones a medida y automatizamos las tareas que se repiten cada semana: presupuestos, facturas, citas, correos y datos. Antes de empezar te decimos cuántas horas ahorras y en cuántos meses se paga.', 'We build custom apps and automate the tasks that repeat every week: quotes, invoices, appointments, emails and data. Before we start, we tell you how many hours you’ll save and how many months it takes to pay for itself.'),
    cta1: { href: '#calculadora', label: T('Calcular mi ahorro', 'Work out my savings'), arrow: '↓' },
    img: { id: 'ia-hero', ph: T('Foto horizontal: oficina de una pyme o persona trabajando con el ordenador', 'Landscape photo: small business office or person working at a computer') },
    facts: [
      { k: T('DIAGNÓSTICO', 'ASSESSMENT'), v: T('Gratuito', 'Free') },
      { k: T('PRIMER PILOTO', 'FIRST PILOT'), v: T('2–4 semanas', '2–4 weeks') },
      { k: T('CÓDIGO Y DATOS', 'CODE AND DATA'), v: T('Tuyos', 'Yours'), hl: true },
    ],
  },
  commit: COMMIT(T('Sin extras. Presupuesto cerrado por escrito.', 'No extras. Fixed quote in writing.')),
  calc: {
    num: T('01 · CALCULADORA DE AHORRO', '01 · SAVINGS CALCULATOR'),
    h: T('¿Cuándo se paga sola?', 'When does it pay for itself?'),
    lead: T('Marca las tareas que hoy hacéis a mano. La calculadora estima las horas que se recuperan y el mes en que el proyecto queda pagado.', 'Select the tasks your team does by hand today. The calculator estimates the hours you get back and the month the project is paid off.'),
    l1: T('01 · TAREAS QUE HACÉIS A MANO', '01 · TASKS YOU DO BY HAND'),
    perPerson: T('h/mes por persona', 'h/month per person'),
    people: T('Personas que las hacen', 'People doing them'),
    rate: T('Coste por hora', 'Cost per hour'),
    resHead: T('SE AMORTIZA EN', 'PAYS FOR ITSELF IN'),
    example: T('ESTIMACIÓN DE EJEMPLO', 'SAMPLE ESTIMATE'),
    hours: T('Horas / mes', 'Hours / month'),
    saving: T('Ahorro / mes', 'Savings / month'),
    project: T('Proyecto', 'Project'),
    costLine: T('COSTE DEL PROYECTO', 'PROJECT COST'),
    cumCap: T('AHORRO ACUMULADO · 12 MESES', 'CUMULATIVE SAVINGS · 12 MONTHS'),
    send: T('Pedir diagnóstico gratuito', 'Request a free assessment'),
    fine: T('Supuesto: se automatiza el 70 % del tiempo de cada tarea. En el diagnóstico medimos tu caso real.', 'Assumption: 70% of each task’s time is automated. The assessment measures your real case.'),
  },
  services: {
    num: T('02 · SERVICIOS', '02 · SERVICES'),
    h: T('Precios de partida.', 'Starting prices.'),
    items: [
      { code: 'IA-01', h: T('Automatización de una tarea', 'Single-task automation'), p: T('Un proceso concreto: presupuestos, facturas o entrada de datos, conectado a los programas que ya usas.', 'One specific process: quotes, invoices or data entry, connected to the software you already use.'), n: T('900 €', '€900'), pre: 'from', post: T('pago único', 'one-off') },
      { code: 'IA-02', h: T('Asistente de atención al cliente', 'Customer service assistant'), p: T('Responde preguntas frecuentes y gestiona citas por web o WhatsApp. Pasa a una persona lo que no sabe.', 'Answers common questions and handles bookings via web or WhatsApp. Hands anything it can’t answer to a person.'), n: T('1.400 €', '€1,400'), pre: 'from', post: T('pago único', 'one-off') },
      { code: 'IA-03', h: T('Aplicación a medida', 'Custom application'), p: T('Una herramienta interna para tu forma de trabajar: pedidos, partes de trabajo, inventario o informes.', 'An internal tool built around how you work: orders, job sheets, inventory or reports.'), n: T('3.500 €', '€3,500'), pre: 'from', post: T('pago único', 'one-off') },
      { code: 'IA-04', h: T('Mantenimiento y soporte', 'Maintenance and support'), p: T('Revisiones, ajustes y soporte con respuesta en 24 h. Sin permanencia.', 'Reviews, tweaks and support with a 24 h response. No lock-in.'), n: T('60 €', '€60'), pre: 'from', post: T('/ mes', '/ month') },
    ],
    foot: T('Precios sin IVA. El presupuesto final se cierra tras el diagnóstico gratuito.', 'Prices exclude VAT. The final quote is fixed after the free assessment.'),
  },
  explain: {
    num: T('03 · QUÉ AUTOMATIZAMOS', '03 · WHAT WE AUTOMATE'),
    h: T('Lo que se repite cada semana y no necesita criterio.', 'Whatever repeats every week and needs no judgement.'),
    paras: [
      T('Copiar datos de un correo a una hoja, preparar el mismo presupuesto con otros números, recordar citas o sacar el informe de cada lunes. Son tareas pequeñas que suman muchas horas al mes.', 'Copying data from an email into a spreadsheet, preparing the same quote with different numbers, sending appointment reminders or pulling the Monday report. Small tasks that add up to many hours a month.'),
      T('Usamos inteligencia artificial donde aporta: leer documentos, clasificar correos o redactar respuestas. Donde no hace falta, usamos reglas simples, que son más baratas y fallan menos.', 'We use artificial intelligence where it adds value: reading documents, sorting emails or drafting replies. Where it isn’t needed, we use simple rules, which are cheaper and fail less.'),
    ],
    img: { id: 'ia-explica', ph: T('Foto: persona en una oficina pequeña con papeles y ordenador', 'Photo: person in a small office with paperwork and a computer'), capR: T('PYME · ANTES DE AUTOMATIZAR', 'SMALL BUSINESS · BEFORE AUTOMATION') },
    dl: [
      [T('EJEMPLOS', 'EXAMPLES'), T('Presupuestos, facturación, citas, atención al cliente, entrada de datos, informes', 'Quotes, invoicing, appointments, customer service, data entry, reports')],
      [T('SE INTEGRA CON', 'INTEGRATES WITH'), T('Correo, hojas de cálculo, tu programa de facturación y tu CRM', 'Email, spreadsheets, your invoicing software and your CRM')],
      [T('DATOS', 'DATA'), T('Alojados en servidores de la Unión Europea', 'Hosted on servers in the European Union')],
    ],
  },
  process: {
    num: T('04 · PROCESO', '04 · PROCESS'),
    h: T('Tres pasos. Pagas cuando ves que funciona.', 'Three steps. You pay when you see it works.'),
    steps: [
      { when: T('SEMANA 1', 'WEEK 1'), h: T('Diagnóstico gratuito', 'Free assessment'), p: T('Medimos cuánto tiempo lleva hoy cada tarea. Te damos horas a ahorrar, precio y plazo de amortización por escrito.', 'We measure how long each task takes today. You get hours to be saved, price and payback period in writing.') },
      { when: T('SEMANAS 2–4', 'WEEKS 2–4'), h: T('Piloto', 'Pilot'), p: T('Ponemos en marcha la primera automatización con tus datos reales y tu equipo la prueba.', 'We launch the first automation with your real data and your team tries it out.') },
      { when: T('MES 2', 'MONTH 2'), h: T('Medición', 'Measurement'), p: T('Comparamos las horas antes y después. Te enseñamos el dato y decides si seguimos.', 'We compare hours before and after. We show you the figures and you decide whether to continue.') },
    ],
  },
  guarantees: {
    num: T('05 · GARANTÍAS', '05 · GUARANTEES'),
    h: T('Por escrito, en el presupuesto.', 'In writing, in the quote.'),
    items: [
      { t: T('Horas medidas', 'Measured hours'), p: T('Medimos el tiempo antes y después del piloto y te entregamos el resultado.', 'We measure time before and after the pilot and hand you the results.') },
      { t: T('Precio cerrado', 'Fixed price'), p: T('Si el trabajo cuesta más de lo previsto, lo asumimos nosotros.', 'If the work costs more than planned, we absorb it.') },
      { t: T('Código y datos tuyos', 'Your code and data'), p: T('Te entregamos el código, los accesos y la documentación. Sin dependencia.', 'We hand over the code, access credentials and documentation. No dependency on us.') },
      { t: T('Datos en la UE', 'Data in the EU'), p: T('Servidores europeos y tratamiento conforme al RGPD. Firmamos contrato de encargado de tratamiento.', 'European servers and GDPR-compliant processing. We sign a data processing agreement.') },
    ],
  },
  company: {
    num: T('06 · LA EMPRESA', '06 · THE COMPANY'),
    p2: T('Todavía no tenemos una cartera larga de clientes, así que no te pedimos que nos creas. Te decimos cuántas horas vas a ahorrar y luego lo medimos delante de ti.', 'We don’t have a long client list yet, so we don’t ask you to take our word for it. We tell you how many hours you’ll save and then measure it in front of you.'),
    person: {
      img: { id: 'ia-responsable', ph: T('Retrato del responsable', 'Project lead portrait') },
      label: T('QUIÉN HACE TU PROYECTO', 'WHO BUILDS YOUR PROJECT'),
      name: T('[Nombre y apellidos]', '[Full name]'),
      role: T('[Cargo] · [Formación o certificaciones]', '[Role] · [Training or certifications]'),
      bio: T('[Dos líneas sobre tu experiencia en desarrollo y automatización.]', '[Two lines about your experience in development and automation.]'),
    },
    extraRows: [],
    nots: [
      T('Vender «IA» donde basta una hoja de cálculo.', 'Selling “AI” where a spreadsheet will do.'),
      T('Dejarte atado a nosotros para que funcione.', 'Leaving you dependent on us to keep it working.'),
      T('Publicar opiniones que no sean de clientes reales.', 'Publishing reviews that aren’t from real clients.'),
    ],
  },
  reviews: {
    num: T('07 · OPINIONES DE CLIENTES', '07 · CLIENT REVIEWS'),
    h: T('Lo que dicen las empresas que ya han automatizado con nosotros.', 'What businesses that have automated with us say.'),
    cap: T('[Nombre] · [Empresa] · [Fecha] · Google', '[Name] · [Company] · [Date] · Google'),
  },
  faq: {
    num: T('08 · PREGUNTAS FRECUENTES', '08 · FREQUENTLY ASKED QUESTIONS'),
    h: T('Las dudas antes de empezar.', 'Questions before you start.'),
    items: [
      [T('¿Mis datos acaban en una IA de fuera?', 'Will my data end up in some outside AI?'), T('No sin que lo sepas. Usamos proveedores con servidores en la Unión Europea y te indicamos por escrito qué datos pasan por cada servicio.', 'Not without you knowing. We use providers with servers in the European Union and tell you in writing which data goes through each service.')],
      [T('¿Tengo que cambiar los programas que uso?', 'Do I have to change the software I use?'), T('Normalmente no. Conectamos lo que ya tienes: correo, hojas de cálculo, programa de facturación o agenda.', 'Usually not. We connect what you already have: email, spreadsheets, invoicing software or calendar.')],
      [T('¿Qué pasa si algo falla?', 'What happens if something fails?'), T('Cada automatización avisa cuando no puede completar una tarea y la deja para una persona. Con mantenimiento, respondemos en 24 h.', 'Every automation alerts you when it can’t finish a task and leaves it for a person. With maintenance, we respond within 24 h.')],
      [T('¿Cuánto tarda en estar funcionando?', 'How long until it’s up and running?'), T('Una automatización sencilla, de 2 a 4 semanas. Una aplicación a medida, según el alcance que cerremos en el diagnóstico.', 'A simple automation takes 2 to 4 weeks. A custom app depends on the scope we agree in the assessment.')],
      [T('¿Y si no ahorro las horas previstas?', 'What if I don’t save the hours you predicted?'), T('Lo verás en la medición del piloto, antes de ampliar nada. Si el resultado no compensa, paramos ahí.', 'You’ll see it in the pilot measurement, before anything is expanded. If the result isn’t worth it, we stop there.')],
      [T('¿Por qué fiarme de una empresa nueva?', 'Why trust a new company?'), T('Porque el diagnóstico es gratuito, el precio es cerrado y el código es tuyo. No dependes de nosotros para seguir funcionando.', 'Because the assessment is free, the price is fixed and the code is yours. You don’t depend on us to keep running.')],
    ],
  },
  contact: {
    num: T('09 · CONTACTO', '09 · CONTACT'),
    lead: T('Cuéntanos qué tareas os quitan tiempo. Te contestamos en 24 h en día laborable.', 'Tell us which tasks eat up your time. We reply within one working day.'),
    services: [T('Diagnóstico gratuito', 'Free assessment'), T('Automatización de una tarea', 'Single-task automation'), T('Asistente de atención al cliente', 'Customer service assistant'), T('Aplicación a medida', 'Custom application')],
  },
  footer: { tagline: T('Apps y automatización con IA para pymes de toda España.', 'Apps and AI automation for small businesses across Spain.'), tag: T('APPS E IA', 'APPS & AI') },
  js: {
    tasks: [
      { id: 'pres', label: T('Presupuestos', 'Quotes'), h: 6 },
      { id: 'fact', label: T('Facturación', 'Invoicing'), h: 5 },
      { id: 'aten', label: T('Atención al cliente', 'Customer service'), h: 12 },
      { id: 'citas', label: T('Gestión de citas', 'Appointment booking'), h: 4 },
      { id: 'datos', label: T('Entrada de datos', 'Data entry'), h: 10 },
      { id: 'inf', label: T('Informes recurrentes', 'Recurring reports'), h: 5 },
    ],
    // Horas/mes por persona y coste de proyecto: valores de ejemplo
    auto: 0.7, base: 900, perTask: 500,
    i18n: {
      month: T('mes', 'month'),
      months: T('meses', 'months'),
      msgHead: T('Datos de la calculadora:', 'Calculator details:'),
      msgTasks: T('Tareas', 'Tasks'),
      msgPeople: T('Personas', 'People'),
      msgRate: T('Coste por hora', 'Cost per hour'),
      msgHours: T('Horas ahorradas estimadas', 'Estimated hours saved'),
      msgPayback: T('Amortización estimada', 'Estimated payback'),
      assessment: T('Diagnóstico gratuito', 'Free assessment'),
    },
  },
};
